### ISSUE TITLE
Master fails tests

### ISSUE THREAD

**Issue by Wicpar** [paulocsanz/arraystring#11]
I just merged my master with yours, since i didn't touch the master and the tests passed when i pushed my const N PR i can only wonder what happened...
Have you run the tests lately, did they succeed ?

**Comment by paulocsanz** [comment]
It should be fixed now, there was an off by one error in remove, when I fixed it it broke other stuff with off by one errors. This bug has existed for years but it was only found now because I reworked Drain to avoid using unsafe.

That's why I'm afraid of changing the inner workings, because it's super hard to reason about correctness (but it's also an argument for removing unsafe, as at least it won't be UB).

**Comment by paulocsanz** [comment]
P

**Comment by paulocsanz** [comment]
Ok it seems to be non-deterministic, it succeeds most of the times but after running a few times it will fail. I will investigate what is going on.

**Comment by Wicpar** [comment]
Yes, i plan to extend the unit tests to be more complete, and extensively verify any rework.
No new test was added for the truncate PR, but as you can nee, all unsafes are behind a proper check. I tried using safe, but the compiler is unable to infer that it will never panic.

**Comment by paulocsanz** [comment]
Yeah, not panicking is a worry of mine. But between panic and being unsound I prefer panic, specially if we can tag it as a cold branch and not inline the panic like std does.

I will take a look at your other PR

**Comment by paulocsanz** [comment]
It actually doesn't seem to be an issue with the tests? But one in cargo itself? It's failing to compile with a linker error, but that is not deterministic. Super weird crash.

![image](https://user-images.githubusercontent.com/6289779/206936660-aa9bb8fc-1e9f-4ba8-9974-8070ab360423.png)

**Comment by Wicpar** [comment]
diesel is not really meant to be used with all 3 backends, we should feature gate them specifically so people can choose which backend to test with, and if one day this crate has github actions we can intall the required env in there for all 3

**Comment by paulocsanz** [comment]
Ok, so closing this issue as it's seems to be resolved
