### ISSUE TITLE
Notes on interesting tools for safe or performant implementation:

### ISSUE THREAD

**Issue by Wicpar** [paulocsanz/arraystring#15]
This is a personal reminder, but if anyone wants to do it first feel free.

- 100% safe panic free truncate with split_at (if the optimizer would be so kind as to know that we already checked if mid > len)
- faster copy with small types creating a custom copy loop: it looks like the use of ptrs in the std function forces the ptrs to actually exist, where an inlined loop would probably be optimized into register operations (please benchmark exhaustively the variato)
- base as many operations as possible with a variation of replace_range if it is properly able to optimize it into the derived ones (remove, insert, push, etc...) (Please see if assembly is identical, or at least performance identical)

**Comment by Wicpar** [comment]
- use slice::align_to(_mut) to align copies if possible, this could x4 or x8 copy performance for pushes and insertions, maybe inner copies if properly aligned. Std functions don't seem to do that.

**Comment by paulocsanz** [comment]
I'm wary of using replace_range, as it's a very complex function and depending on compiler optimizations that may not happen is not ideal. But we can live with it if it makes everything much safer.

I did have a hard time reasoning about replace_range logic as it's very complex though.

Anyway, seems like a great list

**Comment by paulocsanz** [comment]
Using replace_range was the way to go, it seems to have slowed down the lib a bit but the provided safety is totally worth it. We can improve it later by having a replace_range_unchecked or replace_range_truncate, but this works for now.

split_at would be great but I wasn't able to make the compiler strip the panic branch every time.

I'm not sure I follow the copy specialization for small types, could you clarify please?

Did you endup checking the benefits of using align_to on copy performance?

Does it make sense to keep this issue open?

**Comment by Wicpar** [comment]
this was mostly for personal notes so it can be closed.
the align_to is only relevant for large strings, which kind of defeats the purpose of this crate.
All the operations i tried on the array fail to be done in register, they are mostly memory accesses which slows down things tremendously.
The issue i faced during testing is LLVM being unable to keep the array and size as a single register, i think the natural way forward for performance is to test an int based string that uses bitshifts for operations.
My vision of the ideal SmallString is one that exclusively works in a register, never to use a memory access.
a u64 and u128 string should in principle be a lot faster than any other crate.
I'll try to do a proto so we can test that theory.
