### ISSUE TITLE
Why so many usafe unchecked functions ?

### ISSUE THREAD

**Issue by Wicpar** [paulocsanz/arraystring#6]
lots of unchecked functions check things anyway, it makes no sense to have an unsafe version... Can i remove them while i do a refactoring for #5 ?

**Comment by paulocsanz** [comment]
If we can remove unsafety without affecting performance then it's a no-brainer.

If there is a performance issue in production then we should review on a case by case basis.

If you are talking about providing unchecked functions to the user, then it's a different thing. This issue was kinda confusing so I'm not sure I understand what you mean exactly.

**Comment by Wicpar** [comment]
for instance `push_str_unchecked` does all the work necessary for `try_push_str`, the return of a result add negligible overhead, and will be optimized out if used as the basis for `push_str`, that simply truncates the input and unwraps the result.

**Comment by Wicpar** [comment]
as you can see here it produces even better assembly: https://rust.godbolt.org/z/494Mxabax

**Comment by Wicpar** [comment]
also it looks like this could use a maximum of 4 iterations explicitly, generated code unrolls way too far.
```rust
// in truncate_str
while !slice.is_char_boundary(index) {
    index = index.saturating_sub(1);
}
```

**Comment by paulocsanz** [comment]
Nice, if you could provide a PR that would be great, it can be in the same PR but then it will be a bit harder to review. I currently don't have that much free time and don't want to delay your work getting in.

**Comment by Wicpar** [comment]
just tell me if you want to go forward with the #7 style or not, i will change them in a separate PR for now

**Comment by paulocsanz** [comment]
I need some time to review it, I am at work right now and have weekend plans that may prevent me from reviewing, but I will as soon as I can

**Comment by paulocsanz** [comment]
Fixed on main!
